name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t interval-timer-app:latest .
          docker save -o interval-timer-app.tar interval-timer-app:latest

      - name: List files
        run: ls -l

      - name: Set file permissions
        run: chmod 644 interval-timer-app.tar

      - name: Copy Docker image to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "interval-timer-app.tar"
          target: "~/interval-timer-app.tar"
          debug: true
      
      - name: Deploy Docker container on Azure VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker load --input /home/azureuser/interval-timer-app.tar
            sudo docker stop interval-timer || true
            sudo docker rm interval-timer || true
            sudo docker run -d --name interval-timer -p 8080:80 interval-timer-app:latest