name: Build and Deploy React App to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Debug repository structure
    #   run: |
    #     echo "Current Directory:"
    #     pwd
    #     echo "Directory Contents:"
    #     ls -R
    #   working-directory: .  # Root of the repo

    - name: Install dependencies
      run: npm install
      working-directory: .  # Root of the repo

    # - name: Run tests
    #   run: npm test
    #   working-directory: .  # Root of the repo

    - name: Build the React app
      run: npm run build
      working-directory: .  # Root of the repo

    - name: Build Docker image
      run: |
        docker build -t interval-timer-app:latest .
      working-directory: .  # Root of the repo

    - name: Push Docker image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag interval-timer-app:latest ${{ secrets.DOCKER_REGISTRY }}/interval-timer-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_REGISTRY }}/interval-timer-app:${{ github.sha }}
      working-directory: .  # Root of the repo

    - name: Deploy Docker image on Azure VM
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_REGISTRY }}/interval-timer-app:${{ github.sha }}
          docker stop interval-timer-app || true
          docker rm interval-timer-app || true
          docker run -d -p ${{ secrets.PORT }}:80 --name interval-timer-app ${{ secrets.DOCKER_REGISTRY }}/interval-timer-app:${{ github.sha }}
      working-directory: .  # Root of the repo
