name: Build and Deploy React App to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug repository structure
      run: |
        echo "Current Directory:"
        pwd
        echo "Directory Contents:"
        ls -R

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ./interval-timer-app/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install
      working-directory: ./interval-timer-app

    # - name: Run tests
    #   run: npm test
    #   working-directory: ./interval-timer-app

    - name: Build the React app
      run: npm run build
      working-directory: ./interval-timer-app

    - name: Build and push Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_REGISTRY }}/interval-timer-app:${{ github.sha }} ./interval-timer-app
        docker push ${{ secrets.DOCKER_REGISTRY }}/interval-timer-app:${{ github.sha }}

    - name: Deploy Docker image on Azure VM
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT}}
        script: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_REGISTRY }}/interval-timer-app:${{ github.sha }}
          docker stop interval-timer-app || true
          docker rm interval-timer-app || true
          docker run -d -p ${{ secrets.PORT }}:80 --name interval-timer-app ${{ secrets.DOCKER_REGISTRY }}/interval-timer-app:${{ github.sha }}
